networks:
  web:
    external: true
  internal:
    external: false

services:
  cosycreator_mongo:
    image: mongo:7
    container_name: ${SITE_DOMAIN}_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - internal
    labels:
      - traefik.enable=false

  cosycreator_payload:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cosycreator-payload:latest
    container_name: ${SITE_DOMAIN}_payload
    restart: always
    volumes:
      - ./media:/app/media
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://${SITE_DOMAIN}_mongo:27017/cosycreator
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_PUBLIC_SERVER_URL: https://cms.${SITE_DOMAIN}
      NUXT_PUBLIC_SITE_URL: https://${SITE_DOMAIN}
    depends_on:
      - cosycreator_mongo
    networks:
      - internal
      - web
    labels:
      - traefik.http.routers.cosycreator_payload.rule=Host(`cms.${SITE_DOMAIN}`)
      - traefik.http.routers.cosycreator_payload.tls=true
      - traefik.http.routers.cosycreator_payload.tls.certresolver=lets-encrypt
      - traefik.http.services.cosycreator_payload.loadbalancer.server.port=3001

  cosycreator_nuxt:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: cosycreator-nuxt:latest
    restart: always
    environment:
      NODE_ENV: production
      PAYLOAD_BASE_URL: http://${SITE_DOMAIN}_payload:3001
      NUXT_PUBLIC_SITE_URL: https://${SITE_DOMAIN}
    container_name: ${SITE_DOMAIN}_nuxt
    depends_on:
      - cosycreator_payload
    labels:
      - traefik.http.routers.cosycreator_nuxt.rule=Host(`${SITE_DOMAIN}`) || Host(`www.${SITE_DOMAIN}`)
      - traefik.http.routers.cosycreator_nuxt.tls=true
      - traefik.http.routers.cosycreator_nuxt.tls.certresolver=lets-encrypt
      - traefik.http.services.cosycreator_nuxt.loadbalancer.server.port=3000
    networks:
      - web
      - internal

volumes:
  mongo_data: {}
